active_stack_id: 9be8546d-b4d6-4b4a-9510-c0a6c9727025
active_workspace_name: default
analytics_opt_in: true
store:
  api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjU1NjRlNy0yMDMzLTQ3MzAtOTVmZS03ZWY5ZjBlZjhiYmIiLCJpc3MiOiJhMWYyZjBkMC1kOTJkLTRlMTYtYjk2MS1iNDNiMGMzZWYzNWEiLCJhdWQiOiJhMWYyZjBkMC1kOTJkLTRlMTYtYjk2MS1iNDNiMGMzZWYzNWEifQ.C23_fNd3iKj0qdBpifxq27liBAoQAehD0d9RpxEUick
  http_timeout: 30
  password: ''
  secrets_store:
    type: rest
  type: rest
  url: http://127.0.0.1:8237
  username: default
  verify_ssl: true
user_id: a1f2f0d0-d92d-4e16-b961-b43b0c3ef35a
version: 0.50.0
