model_name: decision_tree_regressor
artifact_path: basic_dtr

tag_key: "model"
tag_value: "basic DTR"

module_name: "sklearn.tree"
class_name: "DecisionTreeRegressor"

params:
  criterion: ["friedman_mse", "absolute_error", "poisson"]
  max_depth: [5, 10, 20]
  # min_samples_split: [2, 10, 20]
  # min_samples_leaf: [1, 5, 10]
  max_features: [0.9, "sqrt", "log2"]
  # max_leaf_nodes: [None, 10, 20]
  # min_impurity_decrease: [0.0, 0.01, 0.1]
