model_name: SimpleNet
artifact_path: net_model

tag_key: "model"
tag_value: "SimpleNet"

module_name: "models"
class_name: "SimpleNet"

params:
  module__input_size: [46]
  module__output_size: [1]  
  module__hidden_layer_1: [32, 64, 128]
  module__hidden_layer_2: [16, 32, 64]
  module__hidden_layer_3: [8, 16, 32]
  module__seed: [42]
  max_epochs: [25]
  optimizer__lr: [0.0005]
  optimizer__weight_decay: [10.0]