defaults:
  - _self_
  - data_version
  - test_config
  - ApartmentPrice

data:
  version: v1.0
  remote: localstore
  repo: "."
  path: data/raw/Equity_Apartments_Data.csv 
  sample_size: 0.2
  random_state: 1