defaults:
  - _self_
  - data_version
  - test_config
  - ApartmentPrice
  - sample_data
  - model/model
  - experiment
  - sample_data

data:
  version: v1.0
  remote: localstore
  repo: "."
  path: data/raw/Equity_Apartments_Data.csv
  sample_size: 0.2
  random_state: 1
  target_cols: ["Price"]


paths:
  root_path: /Users/ninelco/Documents/MLOps/ApartmentPrice

hydra:
  mode: MULTIRUN
  # launcher:
  #   n_jobs: -1
  sweeper:
    params:
      # +model: "decision_tree"
      +model: "gbr"
      # +model: "sn"
      # +model: "decision_tree, gbr, sn"

reproducibility:
  seeds:
    - 42
    - 20
    - 1
    - 4
    - 7
    - 10

datasets:
  target_col: "Price"
