defaults:
  - _self_
  - data_version
  - test_config
  - ApartmentPrice
  - sample_data
  - data_version
  - model/model
  - experiment

data:
  version: v1.0
  remote: localstore
  repo: "."
  path: data/raw/Equity_Apartments_Data.csv 
  sample_size: 0.2
  random_state: 1
  target_cols: ["Price"]

hydra:
  mode: MULTIRUN
  # launcher:
  #   n_jobs: -1
  sweeper:
    params:
      # +model: "decision_tree"
      # +model: "gbr"
      +model: "sn"
      # +model: "pr, lr"